### ISSUE TITLE
Π2014010 - Προσθήκη Windows XP & MidnightBSD (A1+A2)

### ISSUE THREAD

**Issue by CptMike** [Cont1nental/site#1]
Περιγραφή συνεισφοράς Α1 + Α2
--
**Μετά απο σκέψη αποφάσισα να συνεισφέρω στο site, προσθέτοντας 2 λειτουργικά συστήματα.** 

**Θέμα διαφάνειας 1:** Windows XP
**Θέμα διαφάνειας 2:** MidnightBSD
**Θέμα σέτ θεματικών διαφανειών:** Λειτουργικά Συστήματα
**Θέμα timeline:** Η εξέλιξη των συστημάτων της Microsoft

**Όνομα:** Παναγιωτίδης Μιχαήλ Π2014010

**Comment by mariosconsta** [comment]
Εύγε! Πολύ καλό!!
