### ISSUE TITLE
Π2015002 - A1 και A2

### ISSUE THREAD

**Issue by mariosconsta** [Cont1nental/site#2]
Θέμα εικόνας 1:  Microsoft DirectX
Θέμα εικόνας 2: GhostBSD
Θέμα σέτ θεματικών διαφανειών: Unix Like Software
Θέμα timeline: Η εξέλιξη των συστημάτων της Microsoft

Όνομα: Κωνσταντίνου Μάριος Π2015002

**Comment by CptMike** [comment]
Σχετικό με το θέμα του μαθήματος. Απο εμένα έχεις το ΟΚ.

**Comment by Sola1r3** [comment]
Και από εμένα παίρνεις το ΟΚ, μπορείς να προχωρήσεις.
