### ISSUE TITLE
Π2014042 - Συμμετοχικό Περιεχόμενο Β1+Β2

### ISSUE THREAD

**Issue by Sola1r3** [Cont1nental/site#9]
Για το δεύτερο παραδοτέο του συμμετοχικού περιεχομένου επέλεξα να γράψω μια βιογραφία για την Margaret Hamilton και σαν μελέτη περίπτωσης ασχολήθηκα με τα windows vista.

[Margaret Hamilton](https://silver-tarsier-ad8cba.netlify.app/biography/margaret-hamilton/)
[Windows Vista](https://silver-tarsier-ad8cba.netlify.app/case-study/vista/)

To netlify στα παραπάνω demo είναι από άλλο branch έχω δύο διαφορετικά demo branch οπότε με το pull και merge θα κλείσω το branch και θα τα μεταφέρω σε άλλο προσωπικό netlify. Για την ώρα όμως δουλεύει ως demo.

**Comment by mariosconsta** [comment]
Όλα καλά! Μπορείς να προχωρίσεις σε Pull Request άμεσα.
